spring:
  application:
    name: eurekagateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: lbservice-route
          uri: lb://lbservice
          predicates:
            - Path=/test/**

server:
  port: 9999

