apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-deployment
  labels:
    app: greet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greet
  template:
    metadata:
      labels:
        app: greet
    spec:
      containers:
      - name: greet
        image: nasihps/greet:v1
        ports:
        - containerPort: 90
