spring:
  application:
    name: lbservice

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      default-zone: http://localhost:8761
    instance:
      hostname: eureka-service